### PR TITLE
Create .packit.yaml

### PR DESCRIPTION
**Pull request by stejskalleos**

### CODE REVIEW

**Comment by nofaralfasi** [comment]
Need to update spec file in foreman-packaging. 
Would you like me to do it? @stejskalleos

**Comment by stejskalleos** [comment]
> Would you like me to do it? @stejskalleos

If you know how to do it, that would be great!

**Comment by nofaralfasi** [comment]
> If you know how to do it, that would be great!

I thought this was the usual error (with the SCL macros). However, this is a different error that I'm not familiar with how to resolve.

**Comment by stejskalleos** [comment]
Fix in packaging: https://github.com/theforeman/foreman-packaging/pull/10578

**Pull request merged**
